name: Links

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  schedule:
    - cron: "0 0 * * 1"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build documentation
        run: npm run build

      - name: Check links
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --verbose
            --no-progress
            --root-dir ./build
            --remap
            '^https://cradle-lang\.org/(.*)$ file://${{ github.workspace }}/build/$1'
            './build/**/*.html'
          fail: true
